// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // All sidebar: links to generated index page
  allSidebar: [
    {
      type: 'category',
      label: 'All',
      link: {
        type: 'generated-index',
        title: 'All Resources',
        description: 'Browse all Islamic resources in one place.',
      },
      items: [{ type: 'autogenerated', dirName: '.' }],
    },
  ],

  // Duas sidebar: links to generated index page
  duasSidebar: [
    {
      type: 'category',
      label: 'Duas',
      link: {
        type: 'generated-index',
        title: 'Duas',
        description: 'All Duas in one place.',
      },
      items: [{ type: 'autogenerated', dirName: 'duas' }],
    },
  ],

  // Ziyarat sidebar: links to generated index page
  ziyaratSidebar: [
    {
      type: 'category',
      label: 'Ziyarat',
      link: {
        type: 'generated-index',
        title: 'Ziyarat',
        description: 'All Ziyarat resources in one place.',
      },
      items: [{ type: 'autogenerated', dirName: 'ziyarat' }],
    },
  ],

  // Example of manual sidebar (commented out)
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
};

export default sidebars;
